### ISSUE TITLE
add contributing instructions to README.md

### ISSUE THREAD

**Issue by jwjeffr** [MUEXLY/MUEXLY.github.io#1]
describe how to add student bio with some quick references to markdown syntax

**Comment by LoiueFragosoUwUr** [comment]
Hi, I am Luis Fernando and I've seen your issue. 
I've already downloaded the repo. However, I'm no idea about what to do next.

**Comment by LoiueFragosoUwUr** [comment]
What do I have to execute?
![image](https://github.com/MUEXLY/MUEXLY.github.io/assets/126754704/e47059f5-4908-4d2c-9911-561bf8af3eac)

**Comment by LoiueFragosoUwUr** [comment]
I've already installed hugo for this project

**Comment by jwjeffr** [comment]
Hey Luis,

This issue is for adding instructions on adding a personal biography on the website as a graduate student in our research group.

So, there isn't anything to execute. There just needs to be instructions in the root's README.md file for adding an index.md file at content/teams/{name}.

If you want to do this, feel free, but the task is probably more fit for someone internal to the research group.

**Comment by jwjeffr** [comment]
Completed with https://github.com/MUEXLY/MUEXLY.github.io/commit/7cfe3dafd811ae715335fd337f5d5a1408af38c4
